services:
  www:
    build: .
    ports:
      - "4040:80"
    volumes:
      - ./www:/var/www/html/
  db:
    image: mysql
    ports:
      - "3303:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql/:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M